name: ssm
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip>=22
  - matplotlib
  - pytorch
  - seaborn
  - transformers
  - datasets
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip:
    - einops
    - flax
    - gcsfs
    - git+https://github.com/geomstats/geomstats/commit/d3ecbc7d2f5e1ae74124a9e1987041272148a185
    - jax
    - optax
    - pytest
    - tqdm
    - wandb
