name: ssm
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip>=22
  - matplotlib
  - seaborn
  - transformers
  - datasets
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tensorflow
  - pip:
    - chex
    - dm-haiku
    - einops
    - jax
    - optax
    - pytest
    - tqdm
    - wandb
