description: "Small model to test"

gcs:
  project: simplex-score-matching

data:
    epochs: 20
    dataset_path: "/home/dashiell/train"
    batch_size: 64
    seq_len: 256
    init_prob_concentration: 0.9

tokenizer:
    path: "tokenizer/tokenizer-wiki8192.json"
    vocab_size: 8192

model:
    type: transformer
    num_layers: 3
    num_heads: 8
    embed_dim: 512
    init_dim: 512
    model_dim: 512
    mlp_dim: 2048
    time_dim: 16
    dropout: 0.1
    attention_dropout: 0.1

optimizer:
    algo: AdamW
    lr: 0.001
    grad_clip: 2.0
